### ISSUE TITLE
K3 runtime cpp cannot compile with Boost 1.59.0

### ISSUE THREAD

**Issue by yliu120** [DaMSL/K3#2]
I have tested linking K3 runtime cpp with boost 1.55, 1.58, 1.59. The result is K3 compiles successfully with Boost 1.55 and 1.58 but failed with 1.59.

I simply copied the compile error message here.

---

[  4%] Building CXX object CMakeFiles/k3.dir/src/core/Engine.cpp.o
In file included from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/detail/preprocessor/enum_params.hpp:19:0,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/detail/preprocessor/preprocessor.hpp:47,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/detail/io/information.hpp:50,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/binary_iarchive.hpp:46,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/serialization/YAS.hpp:5,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/Common.hpp:21,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/core/Engine.hpp:10,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/src/core/Engine.cpp:7:
/home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/detail/preprocessor/repeat.hpp:43:58: error: expected constructor, destructor, or type conversion before ‘(’ token
 # define YAS_PP_REPEAT_1_I(c, m, d) YAS_PP_REPEAT_1_ ## c(m, d)
                                                          ^
/home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/detail/preprocessor/repeat.hpp:38:35: note: in expansion of macro ‘YAS_PP_REPEAT_1_I’
 # define YAS_PP_REPEAT_1(c, m, d) YAS_PP_REPEAT_1_I(c, m, d)
                                   ^
/home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/detail/preprocessor/cat.hpp:29:32: note: in expansion of macro ‘YAS_PP_REPEAT_1’
 #    define YAS_PP_CAT_I(a, b) a ## b
                                ^
/home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/detail/preprocessor/cat.hpp:22:30: note: in expansion of macro ‘YAS_PP_CAT_I’
 #    define YAS_PP_CAT(a, b) YAS_PP_CAT_I(a, b)
                              ^
/home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/detail/preprocessor/repeat.hpp:29:24: note: in expansion of macro ‘YAS_PP_CAT’
 # define YAS_PP_REPEAT YAS_PP_CAT(YAS_PP_REPEAT_, YAS_PP_AUTO_REC(YAS_PP_REPEAT_P, 4))
                        ^
/home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/serializers/binary/boost/boost_fusion_list_serializers.hpp:126:2: note: in expansion of macro ‘YAS_PP_REPEAT’
  YAS_PP_REPEAT( \
  ^
/home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/serializers/binary/boost/boost_fusion_list_serializers.hpp:158:1: note: in expansion of macro ‘YAS__BINARY__GENERATE_SAVE_SERIALIZE_LIST_SPEC_VARIADICS’
 YAS__BINARY__GENERATE_SAVE_SERIALIZE_LIST_SPEC_VARIADICS(FUSION_MAX_LIST_SIZE)
 ^
In file included from /cm/shared/apps/boost/1.5.9/include/boost/bind/mem_fn.hpp:25:0,
                 from /cm/shared/apps/boost/1.5.9/include/boost/mem_fn.hpp:22,
                 from /cm/shared/apps/boost/1.5.9/include/boost/function/detail/prologue.hpp:18,
                 from /cm/shared/apps/boost/1.5.9/include/boost/function/function_template.hpp:13,
                 from /cm/shared/apps/boost/1.5.9/include/boost/function/detail/maybe_include.hpp:18,
                 from /cm/shared/apps/boost/1.5.9/include/boost/function/function1.hpp:11,
                 from /cm/shared/apps/boost/1.5.9/include/boost/program_options/value_semantic.hpp:13,
                 from /cm/shared/apps/boost/1.5.9/include/boost/program_options/options_description.hpp:13,
                 from /cm/shared/apps/boost/1.5.9/include/boost/program_options.hpp:15,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/Options.hpp:8,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/core/Engine.hpp:11,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/src/core/Engine.cpp:7:
/cm/shared/apps/boost/1.5.9/include/boost/get_pointer.hpp:43:28: error: expected ‘}’ before end of line
 #pragma GCC diagnostic push
                            ^
/cm/shared/apps/boost/1.5.9/include/boost/get_pointer.hpp:43:28: error: expected ‘}’ before end of line
/cm/shared/apps/boost/1.5.9/include/boost/get_pointer.hpp:43:28: error: expected declaration before end of line
In file included from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/serializers/binary/std/std_wstring_serializers.hpp:40:0,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/serializers/std_types_serializers.hpp:65,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/serialization/YAS.hpp:9,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/Common.hpp:21,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/core/Engine.hpp:10,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/src/core/Engine.cpp:7:
/home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/detail/tools/utf8conv.hpp: In instantiation of ‘void yas::detail::to_utf8(D&, const S&) [with D = boost::container::basic_string<char, std::char_traits<char>, boost::container::new_allocator<char> >; S = boost::container::basic_string<wchar_t, std::char_traits<wchar_t>, boost::container::new_allocator<wchar_t> >]’:
/home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/detail/tools/utf8conv.hpp:100:19:   required from here
/home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/detail/tools/utf8conv.hpp:21:28: error: invalid use of incomplete type ‘const class boost::container::basic_string<wchar_t, std::char_traits<wchar_t>, boost::container::new_allocator<wchar_t> >’
  for ( auto it = src.begin(); it != src.end(); ++it ) {
                            ^
In file included from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/detail/tools/utf8conv.hpp:11:0,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/serializers/binary/std/std_wstring_serializers.hpp:40,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/serializers/std_types_serializers.hpp:65,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/serialization/YAS.hpp:9,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/Common.hpp:21,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/core/Engine.hpp:10,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/src/core/Engine.cpp:7:
/cm/shared/apps/boost/1.5.9/include/boost/container/container_fwd.hpp:173:7: error: declaration of ‘const class boost::container::basic_string<wchar_t, std::char_traits<wchar_t>, boost::container::new_allocator<wchar_t> >’
 class basic_string;
       ^
In file included from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/serializers/binary/std/std_wstring_serializers.hpp:40:0,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/serializers/std_types_serializers.hpp:65,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/serialization/YAS.hpp:9,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/Common.hpp:21,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/core/Engine.hpp:10,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/src/core/Engine.cpp:7:
/home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/detail/tools/utf8conv.hpp:21:34: error: invalid use of incomplete type ‘const class boost::container::basic_string<wchar_t, std::char_traits<wchar_t>, boost::container::new_allocator<wchar_t> >’
  for ( auto it = src.begin(); it != src.end(); ++it ) {
                                  ^
In file included from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/detail/tools/utf8conv.hpp:11:0,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/serializers/binary/std/std_wstring_serializers.hpp:40,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/serializers/std_types_serializers.hpp:65,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/serialization/YAS.hpp:9,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/Common.hpp:21,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/core/Engine.hpp:10,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/src/core/Engine.cpp:7:
/cm/shared/apps/boost/1.5.9/include/boost/container/container_fwd.hpp:173:7: error: declaration of ‘const class boost::container::basic_string<wchar_t, std::char_traits<wchar_t>, boost::container::new_allocator<wchar_t> >’
 class basic_string;
       ^
In file included from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/serializers/binary/std/std_wstring_serializers.hpp:40:0,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/serializers/std_types_serializers.hpp:65,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/serialization/YAS.hpp:9,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/Common.hpp:21,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/core/Engine.hpp:10,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/src/core/Engine.cpp:7:
/home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/detail/tools/utf8conv.hpp:24:8: error: no match for ‘operator+=’ (operand types are ‘boost::container::basic_string<char, std::char_traits<char>, boost::container::new_allocator<char> >’ and ‘std::basic_string<char>::value_type {aka char}’)
    dst += (std::string::value_type)nchar;
        ^
/home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/detail/tools/utf8conv.hpp:26:8: error: no match for ‘operator+=’ (operand types are ‘boost::container::basic_string<char, std::char_traits<char>, boost::container::new_allocator<char> >’ and ‘int’)
    dst += (0xC0 | (nchar >> 6));
        ^
/home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/detail/tools/utf8conv.hpp:27:8: error: no match for ‘operator+=’ (operand types are ‘boost::container::basic_string<char, std::char_traits<char>, boost::container::new_allocator<char> >’ and ‘int’)
    dst += (0x80 | (nchar & 0x3F));
        ^
/home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/detail/tools/utf8conv.hpp:31:8: error: no match for ‘operator+=’ (operand types are ‘boost::container::basic_string<char, std::char_traits<char>, boost::container::new_allocator<char> >’ and ‘int’)
    dst += (0xE0 | (nchar >> 12));
        ^
/home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/detail/tools/utf8conv.hpp:32:8: error: no match for ‘operator+=’ (operand types are ‘boost::container::basic_string<char, std::char_traits<char>, boost::container::new_allocator<char> >’ and ‘int’)
    dst += (0x80 | ((nchar >> 6) & 0x3F));
        ^
/home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/detail/tools/utf8conv.hpp:33:8: error: no match for ‘operator+=’ (operand types are ‘boost::container::basic_string<char, std::char_traits<char>, boost::container::new_allocator<char> >’ and ‘int’)
    dst += (0x80 | (nchar & 0x3F));
        ^
/home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/detail/tools/utf8conv.hpp:35:8: error: no match for ‘operator+=’ (operand types are ‘boost::container::basic_string<char, std::char_traits<char>, boost::container::new_allocator<char> >’ and ‘int’)
    dst += (0xF0 | (nchar >> 18));
        ^
/home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/detail/tools/utf8conv.hpp:36:8: error: no match for ‘operator+=’ (operand types are ‘boost::container::basic_string<char, std::char_traits<char>, boost::container::new_allocator<char> >’ and ‘int’)
    dst += (0x80 | ((nchar >> 12) & 0x3F));
        ^
/home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/detail/tools/utf8conv.hpp:37:8: error: no match for ‘operator+=’ (operand types are ‘boost::container::basic_string<char, std::char_traits<char>, boost::container::new_allocator<char> >’ and ‘int’)
    dst += (0x80 | ((nchar >> 6) & 0x3F));
        ^
/home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/detail/tools/utf8conv.hpp:38:8: error: no match for ‘operator+=’ (operand types are ‘boost::container::basic_string<char, std::char_traits<char>, boost::container::new_allocator<char> >’ and ‘int’)
    dst += (0x80 | (nchar & 0x3F));
        ^
/home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/detail/tools/utf8conv.hpp: In instantiation of ‘void yas::detail::from_utf8(D&, const S&) [with D = boost::container::basic_string<wchar_t, std::char_traits<wchar_t>, boost::container::new_allocator<wchar_t> >; S = boost::container::basic_string<char, std::char_traits<char>, boost::container::new_allocator<char> >]’:
/home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/detail/tools/utf8conv.hpp:107:21:   required from here
/home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/detail/tools/utf8conv.hpp:47:28: error: invalid use of incomplete type ‘const class boost::container::basic_string<char, std::char_traits<char>, boost::container::new_allocator<char> >’
  for ( auto it = src.begin(); it != src.end(); ++it ) {
                            ^
In file included from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/detail/tools/utf8conv.hpp:11:0,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/serializers/binary/std/std_wstring_serializers.hpp:40,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/serializers/std_types_serializers.hpp:65,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/serialization/YAS.hpp:9,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/Common.hpp:21,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/core/Engine.hpp:10,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/src/core/Engine.cpp:7:
/cm/shared/apps/boost/1.5.9/include/boost/container/container_fwd.hpp:173:7: error: declaration of ‘const class boost::container::basic_string<char, std::char_traits<char>, boost::container::new_allocator<char> >’
 class basic_string;
       ^
In file included from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/serializers/binary/std/std_wstring_serializers.hpp:40:0,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/serializers/std_types_serializers.hpp:65,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/serialization/YAS.hpp:9,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/Common.hpp:21,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/core/Engine.hpp:10,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/src/core/Engine.cpp:7:
/home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/detail/tools/utf8conv.hpp:47:34: error: invalid use of incomplete type ‘const class boost::container::basic_string<char, std::char_traits<char>, boost::container::new_allocator<char> >’
  for ( auto it = src.begin(); it != src.end(); ++it ) {
                                  ^
In file included from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/detail/tools/utf8conv.hpp:11:0,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/serializers/binary/std/std_wstring_serializers.hpp:40,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/serializers/std_types_serializers.hpp:65,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/serialization/YAS.hpp:9,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/Common.hpp:21,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/core/Engine.hpp:10,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/src/core/Engine.cpp:7:
/cm/shared/apps/boost/1.5.9/include/boost/container/container_fwd.hpp:173:7: error: declaration of ‘const class boost::container::basic_string<char, std::char_traits<char>, boost::container::new_allocator<char> >’
 class basic_string;
       ^
In file included from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/serializers/binary/std/std_wstring_serializers.hpp:40:0,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/serializers/std_types_serializers.hpp:65,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/serialization/YAS.hpp:9,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/Common.hpp:21,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/core/Engine.hpp:10,
                 from /home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/src/core/Engine.cpp:7:
/home-4/yliu120@jhu.edu/K3/K3/runtime/cpp/include/external/yas/detail/tools/utf8conv.hpp:70:7: error: no match for ‘operator+=’ (operand types are ‘boost::container::basic_string<wchar_t, std::char_traits<wchar_t>, boost::container::new_allocator<wchar_t> >’ and ‘std::basic_string<wchar_t>::value_type {aka wchar_t}’)
   dst += tmp;
       ^
make[2]: **\* [CMakeFiles/k3.dir/src/core/Engine.cpp.o] Error 1
make[1]: **\* [CMakeFiles/k3.dir/all] Error 2
make: **\* [all] Error 2

---
